"""

Revision ID: d208d1bb99c6
Revises: 7dd673d4b101
Create Date: 2024-08-09 13:20:50.242742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd208d1bb99c6'
down_revision: Union[str, None] = '7dd673d4b101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE message_types_enum AS ENUM ('name', 'cpf_cnpj', 'birth_date', 'final');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.Enum('name', 'cpf_cnpj', 'birth_date', 'final', name='message_types_enum'), nullable=False, server_default="name"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
    op.execute("DROP TYPE message_types_enum;")
